services:
  - type: web
    name: rydewitheli-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: TIKTOK_CLIENT_KEY
        value: awbd4nv2b3l6xua4
      - key: TIKTOK_CLIENT_SECRET
        value: kuMrculqeLhclQVUrch0a7iA6KH4BYaE
      - key: REDIRECT_URI
        value: rydewitheli.com/tiktok/callback
