services:
  - type: web
    name: rydewitheli-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: TIKTOK_CLIENT_KEY
        fromEnvVar: TIKTOK_CLIENT_KEY
      - key: TIKTOK_CLIENT_SECRET
        fromEnvVar: TIKTOK_CLIENT_SECRET
      - key: REDIRECT_URI
        fromEnvVar: REDIRECT_URI
